# Generated by Django 4.2.1 on 2023-06-07 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='films', to='films.producer'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 8, 5, 35, 838004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 8, 5, 35, 839412, tzinfo=datetime.timezone.utc)),
        ),
    ]
