# Generated by Django 4.2.3 on 2023-07-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_budget_remove_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
