# Generated by Django 4.2.3 on 2023-07-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_favorite_remove_movie_watched_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watched',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Watched',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
