# Generated by Django 4.2.2 on 2023-06-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Single'), (2, 'Double'), (3, 'Triple'), (4, 'Quad')], default=1),
        ),
    ]
