# Generated by Django 4.2.2 on 2023-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_remove_room_status_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.CharField(max_length=100),
        ),
    ]
