# Generated by Django 4.2.2 on 2023-06-11 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_remove_room_capacity_booking_guests_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests_num',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
